# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N9dPO8M_W-pMJ6HDItIJEkiXVVB28BXp
"""

!pip install gradio
!pip install transformers

import gradio as gr
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

!pip3 install optimum
!pip3 install auto-gptq

model_name_or_path = "TheBloke/Llama-2-7b-Chat-GPTQ"
model = AutoModelForCausalLM.from_pretrained(model_name_or_path, device_map="auto", trust_remote_code=False, revision="main").cuda()
tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, use_fast=True)

def respond(prompt):
    prompt_template=f'''[INST] <<SYS>>
    You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature. If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.
    <</SYS>>
    {prompt}[/INST]
    '''
    input_ids = tokenizer(prompt_template, return_tensors='pt').input_ids.cuda()
    output = model.generate(inputs=input_ids, temperature=0.7, do_sample=True, top_p=0.95, top_k=40, max_new_tokens=512)
    response = tokenizer.decode(output[0])
    return response

iface = gr.Interface(fn=respond, inputs="text", outputs="text",
                     title="Chatbot", description="A simple chatbot using Hugging Face Transformers and Gradio")

iface.launch()

